name: Test

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild clean -scheme TDD\ Example build-for-testing
    - name: Run tests
      run: xcodebuild test-without-building
