name: Test

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild clean -project TDD\ Example.xcodeproj -scheme TDD\ Example -destination "platform=iOS Simulator, OS=latest" build-for-testing
    - name: Run tests
      run: xcodebuild test-without-building
