name: Test

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild clean -project TDD\ Example.xcodeproj -scheme TDD\ Example build-for-testing
    - name: Run tests
      run: xcodebuild -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3'  test-without-building
